add_lunch_combo SimpleX_xt925-user
add_lunch_combo SimpleX_xt925-userdebug
add_lunch_combo SimpleX_xt926-user
add_lunch_combo SimpleX_xt926-userdebug
add_lunch_combo SimpleX_i605-user
add_lunch_combo SimpleX_i605-userdebug

